name: Deploy Branch Preview

on:
  push:
    branches-ignore:
      - main
  delete:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy Preview
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./build
          publish_branch: gh-pages
          destination_dir: preview/${{ github.ref_name }}

  delete-preview:
    if: github.event_name == 'delete'
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Remove Preview
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git clone --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
          cd gh-pages
          rm -rf preview/${{ github.event.ref }}
          git add .
          git commit -m "Remove preview for deleted branch ${{ github.event.ref }}"
          git push
